export const DEFAULT_PLAN_RULE_SET_KEY = "default";

export const defaultPlanRuleSet = {
  key: DEFAULT_PLAN_RULE_SET_KEY,
  version: 2,
  isActive: true,
  investmentTiers: [
    {
      tier: "INITIAL",
      name: "Initial Pool",
      minUsdt: 100,
      maxUsdt: 1999,
      weeklyReturnMinPercent: 2,
      weeklyReturnMaxPercent: 2,
      isActive: true,
    },
    {
      tier: "GROWTH",
      name: "Growth Pool",
      minUsdt: 2000,
      maxUsdt: 4999,
      weeklyReturnMinPercent: 3,
      weeklyReturnMaxPercent: 3,
      isActive: true,
    },
    {
      tier: "PREMIUM",
      name: "Premium Pool",
      minUsdt: 5000,
      maxUsdt: 9999,
      weeklyReturnMinPercent: 5,
      weeklyReturnMaxPercent: 5,
      isActive: true,
    },
  ],
  levelIncomeRules: [
    { level: 1, percent: 5, isActive: true },
    { level: 2, percent: 2, isActive: true },
    { level: 3, percent: 1, isActive: true },
    { level: 4, percent: 0.5, isActive: true },
    { level: 5, percent: 0.5, isActive: true },
    { level: 6, percent: 0.5, isActive: true },
    { level: 7, percent: 0.5, isActive: true },
  ],
  // bonusUsdt is the daily Royalty Club rate; monthly jobs multiply it by days in period.
  salaryRoyaltyRules: [
    {
      tier: "INITIAL",
      royaltyPool: "M1",
      directRequired: 10,
      requiredDirectTier: null,
      bonusUsdt: 50,
      isActive: true,
    },
    {
      tier: "GROWTH",
      royaltyPool: "M2",
      directRequired: 0,
      requiredDirectTier: null,
      bonusUsdt: 150,
      isActive: true,
    },
    {
      tier: "PREMIUM",
      royaltyPool: "M3",
      directRequired: 0,
      requiredDirectTier: null,
      bonusUsdt: 600,
      isActive: true,
    },
    {
      tier: "PREMIUM",
      royaltyPool: "M4",
      directRequired: 0,
      requiredDirectTier: null,
      bonusUsdt: 1500,
      isActive: true,
    },
    {
      tier: "PREMIUM",
      royaltyPool: "M5",
      directRequired: 0,
      requiredDirectTier: null,
      bonusUsdt: 10000,
      isActive: true,
    },
  ],
  terms: {
    withdrawalDay: "Weekly",
    settlementTime: "T+1",
    royaltyWithdrawal: "Daily",
    levelIncomeCycle: "Once per sale and daily withdrawable",
  },
} as const;
