export const DEFAULT_PLAN_RULE_SET_KEY = "default";

export const defaultPlanRuleSet = {
  key: DEFAULT_PLAN_RULE_SET_KEY,
  version: 2,
  isActive: true,
  investmentTiers: [
    {
      tier: "INITIAL",
      name: "Initial Pool",
      minUsdt: 100,
      maxUsdt: 999,
      weeklyReturnMinPercent: 2,
      weeklyReturnMaxPercent: 2,
      isActive: true,
    },
    {
      tier: "GROWTH",
      name: "Growth Pool",
      minUsdt: 1000,
      maxUsdt: 2499,
      weeklyReturnMinPercent: 3,
      weeklyReturnMaxPercent: 3,
      isActive: true,
    },
    {
      tier: "PREMIUM",
      name: "Premium Pool",
      minUsdt: 2500,
      maxUsdt: 4999,
      weeklyReturnMinPercent: 4,
      weeklyReturnMaxPercent: 4,
      isActive: true,
    },
    {
      tier: "APEX",
      name: "Apex Pool",
      minUsdt: 5000,
      maxUsdt: 9999,
      weeklyReturnMinPercent: 5,
      weeklyReturnMaxPercent: 5,
      isActive: true,
    },
    {
      tier: "ELITE",
      name: "Elite Pool",
      minUsdt: 10000,
      maxUsdt: 50000,
      weeklyReturnMinPercent: 7,
      weeklyReturnMaxPercent: 7,
      isActive: true,
    },
  ],
  levelIncomeRules: [
    { level: 1, percent: 5, isActive: true },
    { level: 2, percent: 2, isActive: true },
    { level: 3, percent: 1, isActive: true },
    { level: 4, percent: 0.5, isActive: true },
    { level: 5, percent: 0.5, isActive: true },
    { level: 6, percent: 0.5, isActive: true },
    { level: 7, percent: 0.5, isActive: true },
  ],
  salaryRoyaltyRules: [
    {
      tier: "INITIAL",
      royaltyPool: "R1",
      directRequired: 10,
      requiredDirectTier: null,
      bonusUsdt: 50,
      isActive: true,
    },
    {
      tier: "GROWTH",
      royaltyPool: "R2",
      directRequired: 0,
      requiredDirectTier: null,
      bonusUsdt: 150,
      isActive: true,
    },
    {
      tier: "PREMIUM",
      royaltyPool: "R3",
      directRequired: 0,
      requiredDirectTier: null,
      bonusUsdt: 600,
      isActive: true,
    },
    {
      tier: "APEX",
      royaltyPool: "R4",
      directRequired: 0,
      requiredDirectTier: null,
      bonusUsdt: 1500,
      isActive: true,
    },
    {
      tier: "ELITE",
      royaltyPool: "R5",
      directRequired: 0,
      requiredDirectTier: null,
      bonusUsdt: 10000,
      isActive: true,
    },
  ],
  terms: {
    withdrawalDay: "Weekly",
    settlementTime: "T+1",
    royaltyWithdrawal: "Monthly",
    levelIncomeCycle: "Once per sale and daily withdrawable",
  },
} as const;
